const constants = {
    JOB_HISTORY_SUCCESS: 'JOB_HISTORY_SUCCESS',
    JOB_HISTORY_FAILURE: 'JOB_HISTORY_FAILURE',
    JOB_REBALANCE_SUCCESS: 'JOB_REBALANCE_SUCCESS',
    JOB_REBALANCE_FAILURE: 'JOB_REBALANCE_FAILURE',
    JOB_EXPAND_SUCCESS: 'JOB_EXPAND_SUCCESS',
    JOB_EXPAND_FAILURE: 'JOB_EXPAND_FAILURE',
    JOB_DELETE_SUCCESS: 'JOB_DELETE_SUCCESS',
    JOB_DELETE_FAILURE: 'JOB_DELETE_FAILURE',
    JOB_VALIDATE_SUCCESS: 'JOB_VALIDATE_SUCCESS',
    JOB_VALIDATE_FAILURE: 'JOB_VALIDATE_FAILURE',
    JOB_START_SUCCESS: 'JOB_START_SUCCESS',
    JOB_START_FAILURE: 'JOB_START_FAILURE',
    JOB_STOP_SUCCESS: 'JOB_STOP_SUCCESS',
    JOB_STOP_FAILURE: 'JOB_STOP_FAILURE',
    JOB_LIST_SUCCESS: 'JOB_LIST_SUCCESS',
    JOB_LIST_FAILURE: 'JOB_LIST_FAILURE',
    JOB_ENABLE_SUCCESS: 'JOB_ENABLE_SUCCESS',
    JOB_ENABLE_FAILURE: 'JOB_ENABLE_FAILURE',
    JOB_GET_SUCCESS: 'JOB_GET_SUCCESS',
    JOB_GET_FAILURE: 'JOB_GET_FAILURE'
};

// const socketEvents = require('./actions/WebSocketActionCreator');
//
// socketEvents.forEach(event => constants[event] = event);

module.exports = constants;
